services:
  fw:
    image: fw
    buid: ./fw
    container_name: fw
    networks:
      external-network:
        ipv4_address: 10.5.0.1
      DMZ:
        ipv4_address: 10.5.1.1
      internal-network:
        ipv4_address: 10.5.2.1
    privileged: true
    tty: true

  external:
    image: external
    build: ./external
    container_name: external
    networks:
      external-network:
        ipv4_address: 10.5.0.20
    depends_on:
      - fw
    privileged: true
    tty: true

  dmz1:
    image: dmz1
    build: ./dmz/dmz1
    container_name: dmz1
    networks:
      DMZ:
        ipv4_address: 10.5.1.20
    depends_on:
      - fw
    privileged: true
    tty: true

  dmz2:
  image: dmz2
  build: ./dmz/dmz2
  container_name: dmz2
  networks:
    DMZ:
      ipv4_address: 10.5.1.21
  depends_on:
    - fw
  privileged: true
  tty: true

  internal1:
    image: internal12
    build: ./internal/internal12
    container_name: internal1
    network:
      internal-network:
        ipv4_address: 10.5.2.20
      depends_on:
        - fw
      privileged: true
      tty: true

  internal2:
    image: internal12
    build: ./internal/internal12
    container_name: internal2
    network:
      internal-network:
        ipv4_address: 10.5.2.21
      depends_on:
        - fw
      privileged: true
      tty: true

  internal3:
    image: internal3
    build: ./internal/internal3
    container_name: internal3
    network:
      internal-network:
        ipv4_address: 10.5.2.22
      depends_on:
        - fw
      privileged: true
      tty: true
network:
  external-network:
    driver: bridge
    impam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.254
  DMZ:
    driver: bridge
    impam:
      config:
        - subnet: 10.5.1.0/24
          gateway: 10.5.1.254
  internal-network:
    driver: bridge
    impam:
      config:
        - subnet: 10.5.2.0/24
      gateway: 10.5.2.254
